version: "3.9"
services:
  compiler:
    build: ./compiler-microservice
    ports:
      - "8080:8080"
  parser:
    build: ./parser-microservice
    ports:
      - "5000:5000"
  wavedrom:
    build: ./wavedrom-microservice
    ports:
      - "8081:8081"
  mysqldb:
    build: ./mysql-db
    ports:
      - "8089:3306"
    environment:
      MYSQL_DATABASE: levels
      MYSQL_USER: db_user
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
