version: "3.9"
services:
  compiler-microservice:
    build: ./compiler-microservice
    ports:
      - "8080:8080"
  parser-microservice:
    build: ./parser-microservice
    ports:
      - "5000:5000"
  wavedrom-microservice:
    build: ./wavedrom-microservice
    ports:
      - "8081:8081"
  mysqldb:
    build: ./mysql-db
    ports:
      - "8089:3306"
    environment:
      MYSQL_DATABASE: levels
      MYSQL_USER: db_user
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  crud-microservice:
    build: ./crud-microservice
    ports:
      - "8082:8082"
      # Connection: "db_user:%s@tcp(mysqldb:3306)/levels"
    environment:
      MYSQL_PASS: ${MYSQL_PASS}
  analyzer-microservice:
    build: ./analyzer-microservice
    ports:
      - "8083:8083"
  gateway:
    build: ./gateway-gateway
    ports:
      - "8084:8084"
    # connection :8082