# syntax=docker/dockerfile:1

## Build
FROM golang:1.16-buster AS build

WORKDIR /app

RUN apt update && apt install -y iverilog && rm -rf /var/lib/apt/lists/*

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /go-verilog-compiler

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /go-verilog-compiler /go-verilog-compiler

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/go-verilog-compiler"]
